#%RAML 1.0 NamedExample
  -
    "ID": 1
    "name": Sharath
    "type": business
    "created date": 2023-11-01
    "airmiles": 30
    "address": "12345 GreenSt,Boulder,Colorado,82433,USA"
  -
    "ID": 2
    "name": Damodar
    "type": personal
    "created date": 2023-12-10
    "airmiles": 32
    "address": "345 WhiteSt,Solder,Milano,82433,USA"