#%RAML 1.0 NamedExample
  -
    "name": Sharath
    "type": business
    "airmiles": 30
    "address": "12345 GreenSt,Boulder,Colorado,82433,USA"
  -
    "name": Damodar
    "type": personal
    "airmiles": 32
    "address": "345 WhiteSt,Solder,Milano,82433,USA"
  
  